### ISSUE TITLE
Raspbian Install - error

### ISSUE THREAD

**Issue by Salvocll** [eclipse-fog05/fog05#158]
Hi,
I tried to run the installation on a raspberry pi with raspbian stretch by executing the .sh file but I encountered many problems including installing some python libraries.

Anyone else tried to install to install on a similar system?

**Comment by ilmoro90** [comment]
I had some problems starting fos_linux. Initially it goes up, but after 10 seconds it doesn't work anymore

**Comment by ilmoro90** [comment]
i have a problem with fos_linux. After i had modified plugin ip, i tried to start all 4 services. All goes up minus fos_linux, that produces this error:

```
● fos_linux.service
   Loaded: loaded (/lib/systemd/system/fos_linux.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-02-20 17:47:33 CET; 11s ago
  Process: 1899 ExecStart=/etc/fos/plugins/plugin-os-linux/linux_plugin /etc/fos/plugins/plugin-os-linux/linux_plugin.json (code=exited, status=1/FAILURE)
 Main PID: 1899 (code=exited, status=1/FAILURE)

feb 20 17:47:33 raspberrypi systemd[1]: fos_linux.service: Service RestartSec=100ms expired, scheduling restart.
feb 20 17:47:33 raspberrypi systemd[1]: fos_linux.service: Scheduled restart job, restart counter is at 5.
feb 20 17:47:33 raspberrypi systemd[1]: Stopped fos_linux.service.
feb 20 17:47:33 raspberrypi systemd[1]: fos_linux.service: Start request repeated too quickly.
feb 20 17:47:33 raspberrypi systemd[1]: fos_linux.service: Failed with result 'exit-code'.
feb 20 17:47:33 raspberrypi systemd[1]: Failed to start fos_linux.service.
```

i'm trying to add this node to environment with the other 2 VM

**Comment by gabrik** [comment]
Can you provide the output of the Linux plugin? 
Just `journalctl -u fos_linux -f`
