### ISSUE TITLE
ERROR: grounder returned with non-zero exit status

### ISSUE THREAD

**Issue by ilmoro90** [eclipse-fog05/fog05#167]
Hi, i'm trying to install fog05, following the install.md and build.md file. I started from build as suggest in install.md.
When i ran:

`# opam switch create fos ocaml-base-compiler.4.07.1`

I got the error: 

`[ERROR] Solver failed: "/usr/bin/aspcud /root/.opam/log/solver-in-2562-5f1023
        /root/.opam/log/solver-out-2562-58c514
        -count(removed),-sum(request,version-lag),-count(down),-sum(solution,version-lag),-count(changed)"
        exited with code 1 "ERROR: grounder returned with non-zero exit status"
Switch initialisation failed: clean up? ('n' will leave the switch partially installed) [Y/n] `

It's correct to start from build? is present an automated script to build up the system?
thanks in advance

**Comment by gabrik** [comment]
Hi, thanks for reporting this.

I see that you already asked also in the opam repo (https://github.com/ocaml/opam/issues/3484) 
They suggest to use opam > 2.0
```
$ opam --version
2.0.1
```

You get something similar?

Which Linux  distribution are you using?

**Comment by ilmoro90** [comment]
I'm using Debian 10. It seems that installing ocml by another way, the problem is fixed. I tried:

`# sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)`

instead of:

`apt-get install opam`

**Comment by gabrik** [comment]
Yep, using the command provided by opam always work!
I'm closing this if you think the opam-related issue is solved
