### ISSUE TITLE
Add link to Installation info on Fog05 websites

### ISSUE THREAD

**Issue by bmullan** [eclipse-fog05/fog05#187]
Neither of the following Fog05 web sites have any mention of "Installation":

**1. https://projects.eclipse.org/proposals/eclipse-fog05  
2. https://fog05.io/docs/internals/intro/**  

It was only after going to the GitHub that you even find the word "Install":

**https://github.com/eclipse-fog05/fog05**

where it has a small link to:
**_https://github.com/eclipse-fog05/fog05/blob/master/INSTALL.md_**

I'd suggest that there should be some text & a link to the above Install Link on those first two Fog05 Websites!   

People shouldn't have to search all over to find out how Fog05 is installed?

Brian

**Comment by gabrik** [comment]
Thanks for this issue.

Installation instruction have been added to the website: https://fog05.io/docs/getting-started/installation/

They are reachable from the landing page by just clicking to "Documentation"
