### ISSUE TITLE
Installation failure using Debian packages on Ubuntu 18.04 - unmet dependencies

### ISSUE THREAD

**Issue by bmullan** [eclipse-fog05/fog05#188]
Following these instructions: 
https://fog05.io/docs/getting-started/installation/#from-debian-packages

When I get to installing:
**$ sudo apt install ./fog05-plugin-net-linuxbridge_0.1.0-1_amd64_ubuntu_bionic.deb**

there is a failure due to an unmet dependency (see below).

> fog05-plugin-net-linuxbridge_0.1.0-1_amd64_ub 100%[===============================================================================================>]  16.30K  --.-KB/s    in 0s      
> 
> 2020-04-09 12:12:53 (68.1 MB/s) - ‘fog05-plugin-net-linuxbridge_0.1.0-1_amd64_ubuntu_bionic.deb’ saved [16688/16688]
> 
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Note, selecting 'fog05-plugin-net-linuxbridge' instead of './fog05-plugin-net-linuxbridge_0.1.0-1_amd64_ubuntu_bionic.deb'
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> **The following packages have unmet dependencies:
>  fog05-plugin-net-linuxbridge : Depends: fog05 (= 0.1.0-1) but it is not installable
> E: Unable to correct problems, you have held broken packages**

I did notice that the Github RELEASES says 2 but looking the only one in the RELEASES section is the to pre-release v0.1.0 

Brian

**Comment by gabrik** [comment]
Hi @bmullan,

Can you please provide the output of `apt list --install | grep fog` ?

I think there was some mistake in the automated debian packaging build

Regarding the github releases page it says two beacuse we had a previour release that was done because of a collaborative project, it as not to be considered as a release.

**Comment by bmullan** [comment]
$ **sudo apt list | grep fog**

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

python3-fog05-sdk/now 0.1.0-1 all [installed,local]
ruby-fog/bionic 1.42.0-2 all
ruby-fog-aliyun/bionic 0.2.0-1 all
ruby-fog-atmos/bionic 0.1.0-3 all
ruby-fog-aws/bionic 2.0.0-3 all
ruby-fog-azure/bionic 0.0.2-1 all
ruby-fog-brightbox/bionic 0.7.1-2 all
ruby-fog-cloudatcost/bionic 0.2.3-1 all
ruby-fog-core/bionic 1.45.0-1 all
ruby-fog-dynect/bionic 0.0.2-1 all
ruby-fog-ecloud/bionic 0.1.1-1 all
ruby-fog-google/bionic 0.5.3-1 all
ruby-fog-json/bionic 1.0.0-1 all
ruby-fog-libvirt/bionic 0.3.0-1 all
ruby-fog-local/bionic 0.3.0-1 all
ruby-fog-openstack/bionic 0.1.6-4 all
ruby-fog-powerdns/bionic 0.1.1+debian-1 all
ruby-fog-profitbricks/bionic 0.0.1-2 all
ruby-fog-rackspace/bionic 0.1.1-4 all
ruby-fog-radosgw/bionic 0.0.4-2 all
ruby-fog-riakcs/bionic 0.1.0-2 all
ruby-fog-sakuracloud/bionic 1.7.5-1 all
ruby-fog-serverlove/bionic 0.1.1-2 all
ruby-fog-softlayer/bionic 0.3.17-1 all
ruby-fog-storm-on-demand/bionic 0.1.1-2 all
ruby-fog-terremark/bionic 0.0.3-2 all
ruby-fog-vmfusion/bionic 0.1.0-2 all
ruby-fog-voxel/bionic 0.0.2-2 all
ruby-fog-vsphere/bionic 0.4.0-1 all
ruby-fog-xenserver/bionic 0.2.3-2 all
ruby-fog-xml/bionic 0.1.1-5 all
ruby-fogbugz/bionic 0.2.1-3 all

$ **sudo apt list --installed | grep fog**
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
python3-fog05-sdk/now 0.1.0-1 all [installed,local]

**Comment by gabrik** [comment]
I see, if is missing the fog05 0.1.0, so I guess that if you run this:
```
wget https://github.com/eclipse-fog05/fog05/releases/download/v0.1.0/fog05_0.1.0-1_amd64_ubuntu-bionic.deb
$ sudo apt install ./fog05_0.1.0-1_amd64_ubuntu-bionic.deb
```
You get an error right?

**Comment by bmullan** [comment]
yes "fog05 : Depends: libc6 (>= 2.28) but 2.27-3ubuntu1 is to be installed"

*$ sudo apt install --reinstall ./fog05_0.1.0-1_amd64_ubuntu-bionic.deb*
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'fog05' instead of './fog05_0.1.0-1_amd64_ubuntu-bionic.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
* fog05 : Depends: libc6 (>= 2.28) but 2.27-3ubuntu1 is to be installed*
E: Unable to correct problems, you have held broken packages.

**Comment by gabrik** [comment]
Ok, as expected the issue is in this package, we are triggering a new build with corrected dependencies.

Also when installing fog05 in each node you need to install: agent, linux plugin, linuxbridge_plugin and one of the fdu plugin (the easiest one is usually the LXD).

I'll keep you updated once the fixed package is available

**Comment by bmullan** [comment]
I'm a long time LXD user so using LXD was going to be my main focus.

Thanks Gabriele!

By the way... I hope you saw that LXD v4.0 LTS has been released.   One of
the bigger new features is support via the LXD's API for *both* LXC
containers and
Quemu Virtual Machines !

https://discuss.linuxcontainers.org/t/lxc-4-0-lts-has-been-released/7182

https://ubuntu.com/blog/lxd-4-0-lts-stable-release-is-now-available

There are may other major new features including Routed NIC interface as an
alternative the default LXBR0 bridged interface etc.

Brian

**Comment by gabrik** [comment]
The .deb package was just fixed, also I noticed that there was an error in the plugin installation instructions they were missing some dependencies, to I have also updated the website.

if you now run:
```
wget https://github.com/eclipse-fog05/fog05/releases/download/v0.1.0/fog05_0.1.0-1_amd64_ubuntu-bionic.deb
sudo apt install ./fog05_0.1.0-1_amd64_ubuntu-bionic.deb
```
It should install correctly the package, and consequently also the others, just follow the updated https://fog05.io/docs/getting-started/installation/#from-debian-packages

Regarding LXD we are aware of that and indeed we are planning to support VMs using the same plugin, we have just to check how to deal with images, while for networking we already create our routers and virtual interfaces leveraging the Linux IP tool.

Please let me know if you have any other installation issue
