### ISSUE TITLE
Documentation about Access and Use of FOrcE and FIM 

### ISSUE THREAD

**Issue by bmullan** [eclipse-fog05/fog05#189]
This page:  https://fog05.io/docs/going-deeper/architecture/

talks about:  
- Fog Orchestration Engine (FOrcE)  
- Fog Infrastructure Manager (FIM)  

Maybe I've just not found it yet but is there some documentation about:  
- how someone accesses FOrcE and FIM  
- how someone uses FOrcE and FIM

**Comment by gabrik** [comment]
Hi,

the page that explains how to use and access FIM is https://fog05.io/docs/getting-started/hello-world/

That explains how to use the FIM API to deploy a simple binary application, more examples can be found in this repo: https://github.com/eclipse-fog05/examples
In general for this release, one can access FIM using the Python3 or Go APIs, from which it is possible to list nodes, retrieve their configuration and deploy units on them,

FIM API can be installed using the deb file (for the python3 ones):

```
wget https://github.com/eclipse-fog05/fog05/releases/download/v0.1.0/python3-fog05_0.1.0-1_all.deb 
sudo apt install ./python3-fog05_0.1.0-1_all.deb 
```
Documentation can be found:
- Go https://godoc.org/github.com/eclipse-fog05/api-go/fog05
- Python3 https://eclipse-fog05-python3-client-api.readthedocs.io/en/latest/


Regarding FOrcE there is not yet API as that component is expected to be designed and developed during next iterations and once the code base will migrate to rust.

**Comment by bmullan** [comment]
Just my opinion...
but if the page that explains how to use and access FIM is
https://fog05.io/docs/getting-started/hello-world/

Then at the top of that page it ought to clearly state that?
Such as...


> *To kick off our tour of Eclipse fog05 and to demonstrate use and access
> of the FOG Infrastructure Manager (FIM), we will start with the obligatory
> “hello world” example. *
> *This example will deploy a native component written in python that create
> a file and write “hello, world!” to the file.*
>

**Comment by gabrik** [comment]
Indeed you are right, documentation should be more clear and extended to facilitate users

**Comment by gabrik** [comment]
Update docs: https://github.com/eclipse-fog05/website/pull/18
