### ISSUE TITLE
Add Open Source MANO (OSM) page for FOG05 VIM to README or somewhere in Docs

### ISSUE THREAD

**Issue by bmullan** [eclipse-fog05/fog05#192]
The [ETSI Open Source MANO (OSM)](https://osm.etsi.org/) project lists FOG05 as one of its VIM:

See **_Section 1.3_** of: **https://osm.etsi.org/docs/user-guide/01-quickstart.html#assumptions-about-interaction-with-vims-and-vnfs**

This OSM web page talks more about it:  **https://osm.etsi.org/wikipub/index.php/Eclipse_fog05**

I would assume FOG users would be interested in the combination of ETSI OSM and FOG05

**Comment by gabrik** [comment]
This can be related to #185 

Because of the connector that needs to be updated

**Comment by gabrik** [comment]
Updated docs are in PR: https://github.com/eclipse-fog05/website/pull/18
