### ISSUE TITLE
[BUG] Hello world example failing

### ISSUE THREAD

**Issue by paaguti** [eclipse-fog05/fog05#193]
**Describe the bug**
After installing from Debian packages on a Ubuntu Bionic Cloud Image, I can't make the hello world example running

**To Reproduce**

My fos_deploy.py...

```
import json
import os
import time
from fog05 import FIMAPI
from fog05_sdk.interfaces.FDU import FDU

def read_file(filepath):
    with open(filepath, 'r') as f:
        data = f.read()
    return data

n = '777fe878-f300-49f7-9374-91165c375211'
api = FIMAPI()
desc = json.loads(read_file(os.path.join(os.getcwd(),'fdu_helloworld.json')))

fdu_descriptor = FDU(desc)
fduD = api.fdu.onboard(fdu_descriptor)
fdu_id=fduD.get_uuid()
print ('fdu_id : {}'.format(fdu_id))
time.sleep(2)
inst_info = api.fdu.instantiate(fdu_id, n)
print ('Instance ID : {}'.format(inst_info.get_uuid()))

input('Press enter to terminate')

api.fdu.terminate(inst_info.get_uuid())

api.close()
exit(0)
```
I got the node id from `/etc/fos/plugins/plugin-fdu-lxd/LXD_plugin.json`
**Expected behavior**
I would expect a similar output as in the Web page
**Output**
```ubuntu@fog05:~/Devel$ python3 fos_deploy.py 
fdu_id : 672a8b5c-124e-5b06-93f7-6f8b43ef3334
Traceback (most recent call last):
  File "fos_deploy.py", line 21, in <module>
    inst_info = api.fdu.instantiate(fdu_id, n)
  File "/usr/lib/python3/dist-packages/fog05/fimapi.py", line 1200, in instantiate
    instance_info = self.define(fduid, nodeid)
  File "/usr/lib/python3/dist-packages/fog05/fimapi.py", line 892, in define
    raise ValueError('Got Error {}'.format(res['error']))
ValueError: Got Error 11
```
**Desktop (please complete the following information):**
 - OS: Linux Ubuntu BIONIC Cloud image
 - Version ```
ubuntu@fog05:~/Devel$ uname -a
Linux fog05 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```
 - Involved plugin (eg. KVM, LXD ...)

**Additional context**

**Comment by gabrik** [comment]
Hi @paaguti,

Which version of fog05 are you using? 0.1 or the one from the master branch?

Can you check that the services are running?

```
sudo systemctl status fos_agent
sudo systemctl status fos_linux
sudo systemctl status fos_linuxbridge
sudo systemctl status fos_native
```

**Comment by paaguti** [comment]
```ubuntu@fog05:~$ sudo systemctl status fos_agent
● fos_agent.service
   Loaded: loaded (/lib/systemd/system/fos_agent.service; enabled; vendor preset
   Active: active (running) since Wed 2020-05-13 11:58:57 UTC; 1h 57min left
 Main PID: 798 (agent)
    Tasks: 3 (limit: 2361)
   CGroup: /system.slice/fos_agent.service
           └─798 /etc/fos/agent -c /etc/fos/agent.json -v
```
```ubuntu@fog05:~$ sudo systemctl status fos_linux
● fos_linux.service
   Loaded: loaded (/lib/systemd/system/fos_linux.service; enabled; vendor preset
   Active: active (running) since Wed 2020-05-13 11:58:56 UTC; 1h 46min left
 Main PID: 728 (python3)
    Tasks: 10 (limit: 2361)
   CGroup: /system.slice/fos_linux.service
           └─728 python3 /etc/fos/plugins/plugin-os-linux/linux_plugin /etc/fos/
```

```● fos_linuxbridge.service
   Loaded: loaded (/lib/systemd/system/fos_linuxbridge.service; enabled; vendor 
   Active: active (running) since Wed 2020-05-13 11:58:56 UTC; 1h 46min left
 Main PID: 707 (python3)
    Tasks: 2 (limit: 2361)
   CGroup: /system.slice/fos_linuxbridge.service
           └─707 python3 /etc/fos/plugins/plugin-net-linuxbridge/linuxbridge_plu
```

```ubuntu@fog05:~$ sudo systemctl status fos_native
Unit fos_native.service could not be found.
```
But that seems to be because `fos_native' is _not_ mentioned in [the Installation page](https://fog05.io/docs/getting-started/installation/)

**Comment by gabrik** [comment]
Ok, you are missing, the `Native Plugin` this is why you get that error.
It is true that the Native Plugin is not mentioned in the installation page, but there is a section that shows how to install the FDUs plugin, using the LXD one as example.

In order to run the example, that is a native application you need to install the `Native Plugin`
You can find the debian installed here: https://github.com/eclipse-fog05/fog05/releases/download/v0.1.0/fog05-plugin-fdu-native_0.1.0-1_amd64_ubuntu-bionic.deb

**Comment by paaguti** [comment]
Once I install the `fos-native ` component, I get to the point of having the deployer running.
However:
```
ubuntu@fog05:~/Devel$ python3 fos_helloword.py 
Traceback (most recent call last):
  File "fos_helloword.py", line 5, in <module>
    out.write('Hello, world! It is {}\n'.format(time.time_ns()))
AttributeError: module 'time' has no attribute 'time_ns'
```
because time_ns is new in Python3.7 and you should take into account that bionic ships with
```ubuntu@fog05:~/Devel$ python3 -
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
```
So that should be `time.time()`. With that changed, I can test `fos_helloworld.py` from the shell, but it still doesn't print anything to `/tmp/fos_helloworld` when deployed from the Python script.
Apparently it needs an `out.flush()` to write things out to the file.

Try to correct the documentation, it is a bit frustrating for a newbie like me ;-)

**Comment by gabrik** [comment]
> Once I install the `fos-native ` component, I get to the point of having the deployer running.
> However:
> ....
> Please try to correct the documentation, it is a bit frustrating for a newbie like me ;-)

Sure fill fix it prior to next release

> BTW, this is just an appetizer... I want to test fog05 against OSM :-)

In that case, I suggest that you wait for next release, mid-June, because we have to update the vimconn in OSM to make it work with the changes we have done.

Please refer to #https://github.com/eclipse-fog05/fog05/issues/185

**Comment by paaguti** [comment]
But would the current vimconn work against my installation (i.e. with 0.1.0 .deb packages)? I may only need to be able to register the fog05 in the very near future in order to test other OSM features.. (i.e. no xNF deployment on fog05 for the moment being).

Thx, /PA

**Comment by gabrik** [comment]
The current vimconn works against this branch: https://github.com/eclipse-fog05/fog05/tree/5gcity

But I guess the registration should work, any xNF deployment will not
