### ISSUE TITLE
[BUG]- I am unable to run Zenoh in my RPi. Is there any particular way for that.

### ISSUE THREAD

**Issue by ricktam1469** [eclipse-fog05/fog05#194]
![image](https://user-images.githubusercontent.com/16323105/82205220-d8e4cd80-9923-11ea-9a84-6f8e1b664435.png)

**Comment by gabrik** [comment]
Hi @ricktam1469 I bet the service file is missing.

Can you check with `ls -al /lib/systemd/system/zen*` and check if you have the zenoh directory installed `ls -al /etc/zenoh/`

**Comment by ricktam1469** [comment]
Thanks, 
Yes it is not available. Can you please give me the way, from where I can install this.
As per documentation I am not able to install it. 
Please help.

**Comment by gabrik** [comment]
Before being able to give you a link I need to know if you are running in a 64bit or 32bit arm.

Can you give me the result of `uname -a` for your raspberry pi?

**Comment by ricktam1469** [comment]
Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

**Comment by gabrik** [comment]
Then I'll build one for you and once it is ready I'll share the link.
We do not have any automatic build for `armv7l`

**Comment by ricktam1469** [comment]
Hi, Is there any link available for this. Thanks in advance

**Comment by gabrik** [comment]
Here you can find the binaries:
https://www.dropbox.com/s/3o49wq0a4krrtwj/zenoh.tar.gz

You need to copy the files inside `/etc/zenoh/`

And then you can start it using the `start.sh` script

**Comment by ricktam1469** [comment]
/etc/zenoh/zenohd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /etc/zenoh/zenohd)
 Hi, I am getting this error while running start.sh.

**Comment by gabrik** [comment]
Which version of raspbian are you running?

**Comment by gabrik** [comment]
Can you give me the output of `cat /etc/os-release` ? 

Because I build with the same kernel, but maybe the version of raspian is different and the one you have does not have an up-to-date libc

**Comment by gabrik** [comment]
Please check with this one.


[zenoh.tar.gz](https://github.com/eclipse-fog05/fog05/files/4830568/zenoh.tar.gz)
