### ISSUE TITLE
[BUG] Unable to run helloworld program

### ISSUE THREAD

**Issue by websteroy** [eclipse-fog05/fog05#196]
**Bug Description**
```
user@machine-debian:/helloworld$ ls
fdu_helloworld.json  fos_deploy.py  fos_helloworld.py

user@machine-debian:~/helloworld$ python3 fos_deploy.py
fdu_id : 672a8b5c-124e-5b06-93f7-6f8b43ef3334
Traceback (most recent call last):
  File "fos_deploy.py", line 19, in <module>
    inst_info = api.fdu.instantiate(fduD.get_uuid(), n)
  File "/usr/local/lib/python3.7/dist-packages/fog05-0.1.0-py3.7.egg/fog05/fimapi.py", line 1200, in instantiate
  File "/usr/local/lib/python3.7/dist-packages/fog05-0.1.0-py3.7.egg/fog05/fimapi.py", line 890, in define
  File "/usr/lib/python3/dist-packages/fog05_sdk/yaks_connector.py", line 1246, in define_fdu_in_node
    raise ValueError('Empty data on exec_agent_eval')
ValueError: Empty data on exec_agent_eval
```

**To Reproduce**
1. Go to https://fog05.io/docs/getting-started/installation/
2. Follow the steps to install fog05 using debian packages.
3. Ensure that all services - zenoh, fos_agent, fos_linux, fos_linuxbridge and fos_lxd are running fine using `sudo systemctl status` command.
4. After installation, go to https://fog05.io/docs/getting-started/hello-world/ for the Hello World example. Follow the steps listed there. Note that there is a typo ("fduD") in the python program which leads to a syntax error. Fix that.
5. On running the fos_deploy.py program, you will see the above error.

**Expected behavior**
The FDU should be instantiated and the hello-world program should run.

**Desktop (please complete the following information):**
 - OS: Debian 10 Buster VM on Azure
 - LXD

Can you please guide what the error means here? I tried looking into the code, and it seems like some information is missing, but I cannot tell what.

**Comment by gabrik** [comment]
Hi @websteroy,

It seems similar to this https://github.com/eclipse-fog05/fog05/issues/193

The "hello world" example is `native` application, so it needs the `native` plugin.
It can be found here: https://github.com/eclipse-fog05/fog05/releases/download/v0.1.0/fog05-plugin-net-linuxbridge_0.1.0-1_amd64_debian_10-slim.deb

Once it is installed and started (same as the lxd one, `sudo systemctl start fos_native`) the example should work

**Comment by websteroy** [comment]
Thanks! The following changes made the program work.

1. Installed the fos_native plugin. The link you provided is of the linuxbridge. Here is the correct link: https://github.com/eclipse-fog05/fog05/releases/download/v0.1.0/fog05-plugin-fdu-native_0.1.0-1_amd64_ubuntu-bionic.deb
2. The node-id has to be in 8-4-4-4-12 format. Otherwise, we see the same error. The id present in /etc/machine-id is not in this format.
3. As mentioned in #193 the hello-world program needs a flush call to allow it to write to the file.
