### ISSUE TITLE
[BUG] REST call DELETE /flavor does/<flv_id>/info doesn't remove flavor

### ISSUE THREAD

**Issue by lorenzoblasi** [eclipse-fog05/fog05#198]
**Describe the bug**
The code for DELETE /flavors/<flv_id>/info seems to be wrong

**To Reproduce**
The code in https://github.com/eclipse-fog05/fog05/blob/master/src/utils/python/rest_proxy/src/service.py is:

            res = json.dumps(fos_api.fdu.flavor(flv_id))

I can't even find any method fos_api.fdu.flavor: this code should produce an exception if executed...

**Expected behavior**
I think the code should have been:

            res = json.dumps(fos_api.flavor.remove(flv_id))

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
Nice code anyway :)

**Comment by gabrik** [comment]
Thank @lorenzoblasi for spotting this, Indeed it is a bug.

**Comment by gabrik** [comment]
fixed by #201
