### ISSUE TITLE
Ubuntu 18.04 Hello World! Question

### ISSUE THREAD

**Issue by s9013xx** [eclipse-fog05/fog05#209]
Hi Sirs

I want to run the Hello World! sample from the website (https://fog05.io/docs/getting-started/hello-world/), when I install the fog05-plugin-fdu-containerd_0.2.1-1_amd64.deb, I got the  dependency error : "fog05-plugin-fdu-containerd : Depends: fog05 (>= 0.2.0) but it is not installable".

So how can I install the fog05>-0.2.0 package?  I already follow and finish the installation guide (https://fog05.io/docs/getting-started/installation/) from source.

Thank you!

**Comment by gabrik** [comment]
The `.deb` checks if the agent is installed via the classical `apt` dependency system.
So you should install all the components using the `.deb` files not mixing source installation and `.deb` installation.

You can find the debian packages in this page: https://github.com/eclipse-fog05/fog05/releases/tag/v0.2.2

**Comment by s9013xx** [comment]
Okay, I got it!

Thank you!
