### ISSUE TITLE
[Question] LXD deployment fails

### ISSUE THREAD

**Issue by tommyliverani** [eclipse-fog05/fog05#210]
I had an unexpected beahvior with deploying a lxd container.
If I deploy it using the default profile(with lxc launch <image name>) It works correctly.
If I deploy it with fog05 it can't make an http request.

Is there any way to deploy a container using the default profile?

That's my fdu descriptor:

<img width="370" alt="fdu" src="https://user-images.githubusercontent.com/43218487/104209359-e6f6d980-5431-11eb-8af1-1b4dd42ef30a.PNG">

**Comment by gabrik** [comment]
Hi @tommyliverani

That descriptor will deploy using something very very similar to the `default` profile of LXD.


Can you get the output of the LXD plugin when deploying? 
This command allows you to get the output: `sudo journalctl -u fos_lxd -f`

**Comment by tommyliverani** [comment]
gen 12 09:59:55 tommy-VirtualBox fos_lxd[980]: [2021-01-12 09:59:55,764] - [INFO] > < __fdu_observer() >  LXD Plugin - New Action of a FDU - FDU Info: {'uuid': 'c9a9e478-31e6-4712-b362-b6d4f8572ad3', 'fdu_id': 'd790a23d-ee56-5645-8c8d-fb014d9c4776', 'status': 'DEFINE', 'image': {'uri': 'file:////home/tommy/Desktop/sprint3/fog_node.tar.gz', 'checksum': '', 'format': 'tar.gz'}, 'storage': [], 'computation_requirements': {'cpu_arch': 'x86_64', 'cpu_min_freq': 0, 'cpu_min_count': 1, 'ram_size_mb': 128.0, 'storage_size_gb': 5.0}, 'hypervisor': 'LXD', 'migration_kind': 'COLD', 'interfaces': [{'name': 'eth0', 'is_mgmt': True, 'if_type': 'INTERNAL', 'virtual_interface': {'intf_type': 'BRIDGED', 'vpci': 'lxdbr0', 'bandwidth': 10}, 'vintf_name': 'eth0', 'status': 'CREATE', 'phy_face': 'lxdbr0'}], 'io_ports': [], 'connection_points': [], 'depends_on': [], 'hypervisor_info': {}}
gen 12 09:59:55 tommy-VirtualBox fos_lxd[980]: [2021-01-12 09:59:55,764] - [INFO] > < __fdu_observer() >  LXD Plugin - This is a define for : {'uuid': 'c9a9e478-31e6-4712-b362-b6d4f8572ad3', 'fdu_id': 'd790a23d-ee56-5645-8c8d-fb014d9c4776', 'status': 'DEFINE', 'image': {'uri': 'file:////home/tommy/Desktop/sprint3/fog_node.tar.gz', 'checksum': '', 'format': 'tar.gz'}, 'storage': [], 'computation_requirements': {'cpu_arch': 'x86_64', 'cpu_min_freq': 0, 'cpu_min_count': 1, 'ram_size_mb': 128.0, 'storage_size_gb': 5.0}, 'hypervisor': 'LXD', 'migration_kind': 'COLD', 'interfaces': [{'name': 'eth0', 'is_mgmt': True, 'if_type': 'INTERNAL', 'virtual_interface': {'intf_type': 'BRIDGED', 'vpci': 'lxdbr0', 'bandwidth': 10}, 'vintf_name': 'eth0', 'status': 'CREATE', 'phy_face': 'lxdbr0'}], 'io_ports': [], 'connection_points': [], 'depends_on': [], 'hypervisor_info': {}}
gen 12 09:59:55 tommy-VirtualBox fos_lxd[980]: [2021-01-12 09:59:55,764] - [INFO] > < define_fdu() >  LXD Plugin - Defining a Container
gen 12 10:01:17 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:01:17,131] - [INFO] > < define_fdu() > [ INFO ] LXD Plugin - Loading image data from: /var/fos/lxd/images/fog_node.tar.gz
gen 12 10:01:49 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:01:49,870] - [INFO] > < define_fdu() > [ DONE ] LXD Plugin - Loaded image data from: /var/fos/lxd/images/fog_node.tar.gz
gen 12 10:01:49 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:01:49,873] - [INFO] > < define_fdu() > [ INFO ] LXD Plugin - Creating image with alias d790a23d-ee56-5645-8c8d-fb014d9c4776
gen 12 10:03:32 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:03:32,281] - [INFO] > < define_fdu() > [ DONE ] LXD Plugin - Created image with alias d790a23d-ee56-5645-8c8d-fb014d9c4776
gen 12 10:03:32 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:03:32,419] - [INFO] > < define_fdu() > [ DONE ] LXD Plugin - Container uuid: c9a9e478-31e6-4712-b362-b6d4f8572ad3
gen 12 10:03:32 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:03:32,750] - [INFO] > < __fdu_observer() >  LXD Plugin - New Action of a FDU - FDU Info: {'uuid': 'c9a9e478-31e6-4712-b362-b6d4f8572ad3', 'fdu_id': 'd790a23d-ee56-5645-8c8d-fb014d9c4776', 'status': 'CONFIGURE', 'image': {'uri': 'file:////home/tommy/Desktop/sprint3/fog_node.tar.gz', 'checksum': '', 'format': 'tar.gz'}, 'storage': [], 'computation_requirements': {'cpu_arch': 'x86_64', 'cpu_min_freq': 0, 'cpu_min_count': 1, 'ram_size_mb': 128.0, 'storage_size_gb': 5.0}, 'hypervisor': 'LXD', 'migration_kind': 'COLD', 'interfaces': [{'name': 'eth0', 'is_mgmt': True, 'if_type': 'INTERNAL', 'virtual_interface': {'intf_type': 'BRIDGED', 'vpci': 'lxdbr0', 'bandwidth': 10}, 'vintf_name': 'eth0', 'status': 'CREATE', 'phy_face': 'lxdbr0'}], 'io_ports': [], 'connection_points': [], 'depends_on': [], 'hypervisor_info': {}}
gen 12 10:03:32 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:03:32,750] - [INFO] > < configure_fdu() >  LXD Plugin - Configure a Container uuid c9a9e478-31e6-4712-b362-b6d4f8572ad3
gen 12 10:03:32 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:03:32,777] - [INFO] > < configure_fdu() > [ INFO ] LXD Plugin - Creating profile...
gen 12 10:03:32 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:03:32,808] - [INFO] > < __generate_custom_profile_devices_configuration() > Interface Info {'name': 'eth0', 'is_mgmt': True, 'if_type': 'INTERNAL', 'virtual_interface': {'intf_type': 'BRIDGED', 'vpci': 'lxdbr0', 'bandwidth': 10}, 'vintf_name': 'eth0', 'status': 'CREATE', 'phy_face': 'lxdbr0'}
gen 12 10:03:32 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:03:32,823] - [INFO] > < __generate_custom_profile_devices_configuration() > LXD Plugin - Container Devices {'eth0': {'name': 'eth0', 'type': 'nic', 'parent': 'lxdbr0', 'nictype': 'bridged', 'hwaddr': '00:16:16:72:04:03'}, 'root': {'path': '/', 'type': 'disk', 'pool': 'default', 'size': '5GB'}}
gen 12 10:03:32 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:03:32,823] - [INFO] > < configure_fdu() > [ INFO ] Profile devices {'eth0': {'name': 'eth0', 'type': 'nic', 'parent': 'lxdbr0', 'nictype': 'bridged', 'hwaddr': '00:16:16:72:04:03'}, 'root': {'path': '/', 'type': 'disk', 'pool': 'default', 'size': '5GB'}}
gen 12 10:03:32 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:03:32,823] - [INFO] > < __generate_custom_profile_devices_configuration() > LXD Plugin - Devices {'eth0': {'name': 'eth0', 'type': 'nic', 'parent': 'lxdbr0', 'nictype': 'bridged', 'hwaddr': '00:16:16:72:04:03'}, 'root': {'path': '/', 'type': 'disk', 'pool': 'default', 'size': '5GB'}}
gen 12 10:03:32 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:03:32,883] - [INFO] > < configure_fdu() > [ DONE ] LXD Plugin - Creating profile...
gen 12 10:03:32 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:03:32,883] - [INFO] > < configure_fdu() > [ INFO ] LXD Plugin - Generating container configuration...
gen 12 10:03:32 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:03:32,883] - [INFO] > < __generate_container_dict() > LXD Plugin - Container Configuration {'name': 'cc9a9e478-31e6-4712-b362-b6d4f8572ad3', 'profiles': ['c9a9e478-31e6-4712-b362-b6d4f8572ad3'], 'source': {'type': 'image', 'alias': 'd790a23d-ee56-5645-8c8d-fb014d9c4776'}}
gen 12 10:03:32 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:03:32,883] - [INFO] > < configure_fdu() > [ DONE ] LXD Plugin - Generating container configuration...
gen 12 10:03:32 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:03:32,883] - [INFO] > < configure_fdu() > [ INFO ] LXD Plugin - Creating Container...
gen 12 10:07:56 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:07:56,982] - [INFO] > < configure_fdu() > [ INFO ] LXD Plugin - Container Name cc9a9e478-31e6-4712-b362-b6d4f8572ad3
gen 12 10:07:56 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:07:56,983] - [INFO] > < configure_fdu() > [ DONE ] LXD Plugin - Creating Container...
gen 12 10:07:56 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:07:56,985] - [INFO] > < configure_fdu() > [ INFO ] LXD Plugin - Registreting start/run/log/ls/file evals for c9a9e478-31e6-4712-b362-b6d4f8572ad3
gen 12 10:07:56 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:07:56,986] - [INFO] > < configure_fdu() > [ DONE ] LXD Plugin - Starting a Monitoring of c9a9e478-31e6-4712-b362-b6d4f8572ad3
gen 12 10:07:57 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:07:57,466] - [INFO] > < __monitor_instance() > [ INFO ] LXD Plugin - Updating status of c9a9e478-31e6-4712-b362-b6d4f8572ad3 - cc9a9e478-31e6-4712-b362-b6d4f8572ad3
gen 12 10:08:03 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:08:03,213] - [INFO] > < __monitor_instance() > [ INFO ] LXD Plugin - Updating status of c9a9e478-31e6-4712-b362-b6d4f8572ad3 - cc9a9e478-31e6-4712-b362-b6d4f8572ad3
gen 12 10:08:08 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:08:08,485] - [INFO] > < __monitor_instance() > [ INFO ] LXD Plugin - Updating status of c9a9e478-31e6-4712-b362-b6d4f8572ad3 - cc9a9e478-31e6-4712-b362-b6d4f8572ad3
gen 12 10:08:13 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:08:13,624] - [INFO] > < __monitor_instance() > [ INFO ] LXD Plugin - Updating status of c9a9e478-31e6-4712-b362-b6d4f8572ad3 - cc9a9e478-31e6-4712-b362-b6d4f8572ad3
gen 12 10:08:18 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:08:18,764] - [INFO] > < __monitor_instance() > [ INFO ] LXD Plugin - Updating status of c9a9e478-31e6-4712-b362-b6d4f8572ad3 - cc9a9e478-31e6-4712-b362-b6d4f8572ad3
gen 12 10:08:22 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:08:22,277] - [INFO] > < start_fdu() >  LXD Plugin - Starting a Container uuid c9a9e478-31e6-4712-b362-b6d4f8572ad3
gen 12 10:08:22 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:08:22,277] - [INFO] > < start_fdu() >  LXD Plugin - Environment variables {'environment.MYENV': 'Hello World!'}
gen 12 10:08:22 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:08:22,347] - [INFO] > < start_fdu() > [ INFO ] LXD Plugin - Container Name cc9a9e478-31e6-4712-b362-b6d4f8572ad3
gen 12 10:08:22 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:08:22,670] - [INFO] > < start_fdu() > [ DONE ] LXD Plugin - Starting a Container uuid c9a9e478-31e6-4712-b362-b6d4f8572ad3
gen 12 10:08:23 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:08:23,902] - [INFO] > < __monitor_instance() > [ INFO ] LXD Plugin - Updating status of c9a9e478-31e6-4712-b362-b6d4f8572ad3 - cc9a9e478-31e6-4712-b362-b6d4f8572ad3
gen 12 10:08:29 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:08:29,043] - [INFO] > < __monitor_instance() > [ INFO ] LXD Plugin - Updating status of c9a9e478-31e6-4712-b362-b6d4f8572ad3 - cc9a9e478-31e6-4712-b362-b6d4f8572ad3
gen 12 10:08:34 tommy-VirtualBox fos_lxd[980]: [2021-01-12 10:08:34,317] - [INFO] > < __monitor_instance() > [ INFO ] LXD Plugin - Updating status of c9a9e478-31e6-4712-b362-b6d4f8572ad3 - cc9a9e478-31e6-4712-b362-b6d4f8572ad3

**Comment by gabrik** [comment]
From the log, the container seems running.

Can you see it with `lxc list` ?

**Comment by tommyliverani** [comment]
Yes

**Comment by gabrik** [comment]
Does it show also the IP address?

**Comment by tommyliverani** [comment]
Yes.
I can also start an http server from the container but I can't reach it from outside.
If I do the same without deploying it with fog05 it works correctly.
Also if I launch the image created by fog05 during the deployment It works correctly.

**Comment by gabrik** [comment]
That's odd, in that case, it is connected to the default LXD network so it should be really the same as `lxc launch .... -p default`

Are you able to ping the container when deployed by fog05?

**Comment by tommyliverani** [comment]
Yes

**Comment by gabrik** [comment]
Then it is even more strange.

Can you post the output of `lxc list`, `sudo iptables -t nat -L -n -v` and `ip link show`

**Comment by tommyliverani** [comment]
<img width="867" alt="lxc list" src="https://user-images.githubusercontent.com/43218487/104305617-30483700-54cd-11eb-912b-dc5e0520c59e.PNG">
<img width="860" alt="iptables" src="https://user-images.githubusercontent.com/43218487/104305624-3211fa80-54cd-11eb-8133-aac2ad77cd4b.PNG">
<img width="862" alt="link" src="https://user-images.githubusercontent.com/43218487/104305630-33dbbe00-54cd-11eb-8610-89b747d07978.PNG">

**Comment by bmullan** [comment]
I don't know FOG that well but I use LXD alot so I could be wrong but your
HOSTs Enps0 doesn't look like it has an IP address ?

Brian

**Comment by gabrik** [comment]
I see that iptables is missing one rule that should be applied by LXD in order to allow NAT and then allowing the container to reach the internet.

It can also be because of the missing address on enp0s3

**Comment by tommyliverani** [comment]
Ok, but in my case the http client is in the same virtual machine as lxd.

**Comment by bmullan** [comment]
If the *Host's enp0s3* does not have an IP address t*he Host's lxdbr0 will
not either... and it does not in this case.*

Having only a MAC address will NOT let routing work (as far as I know but
then maybe FOG does some kind of magic that I don't understand).

[image: image.png]

Brian

**Comment by gabrik** [comment]
Ok, then I guess I misunderstood the error.

You have a client inside the LXD container and you are trying to do an HTTP request, what is the endpoint of this HTTP request?

**Comment by tommyliverani** [comment]
It is a flask server.

I tryed both configuration:
1) making an http request from the container to a flask server in the host machine
2) making an http request from the host machine to the flask server in the container

**Comment by gabrik** [comment]
Ok, got it, does the container ping the machine when instantiated via fog05? 

Also it is worth check the output of `ss -tlpn` in both container and machine

**Comment by tommyliverani** [comment]
yes I can ping in both direction.

Host machine:

<img width="849" alt="hostmachine" src="https://user-images.githubusercontent.com/43218487/104343214-f5a9c300-54fb-11eb-812b-a5efe896c80a.PNG">

Conatiner:
<img width="840" alt="container" src="https://user-images.githubusercontent.com/43218487/104343269-05290c00-54fc-11eb-9e2b-cf1d5c7ff1ce.PNG">

**Comment by bmullan** [comment]
in the above there **are ip addresses even though some are loopback and some are 0.0.0.0**

Go into the container and do an:

**# ip a**

and look at the routes

do the same from the host

**Comment by gabrik** [comment]
Then it is supposed to just work.

Is flask listening to `10.0.2.15:5000` in the host machine? 

I guess the container is unable to ping that address, can you try a `tracepath 10.0.2.15` on the container?

**Comment by tommyliverani** [comment]
I did some more tests and I found that it was not a network problem as I thought but the whole application inside the container stopped.
Sorry for not finding out earlier.
The reason was that the ram_size field was too low and now It works correctly.
I thought that field indicated the minimum requirement needed to deploy but I think I'm wrong.

**Comment by gabrik** [comment]
Glad to hear that it is working now.

The `ram_size_mb` field indeed indicates the amount of memory that will be assigned to the container.

**Comment by tommyliverani** [comment]
Hi @gabrik sorry for the trouble but I have another problem.
I want to connect my container to a physical network and that's  what I'm doing:
<img width="786" alt="descriptro" src="https://user-images.githubusercontent.com/43218487/104616607-c7a6b900-568a-11eb-909d-2bb06edfed2d.PNG">
The container get an ip address correctly but I can't ping it from outside(or ping the host from the container)
<img width="863" alt="list" src="https://user-images.githubusercontent.com/43218487/104616775-ffadfc00-568a-11eb-9b5f-c193406b03ce.PNG">
What I'm doing wrong?

**Comment by gabrik** [comment]
If I'm not wrong, this moves the interface under the container, then the host should not have that interface anymore.

Check it by running `ip l` in both the container and the host

**Comment by tommyliverani** [comment]
<img width="865" alt="ip" src="https://user-images.githubusercontent.com/43218487/104623247-7ac6e080-5692-11eb-98c6-0f7b179a71ac.PNG">

**Comment by gabrik** [comment]
Ok, then I was wrong, it uses MACVLAN that can cause this sort of issue. 
[More on MACVLAN](https://sreeninet.wordpress.com/2016/05/29/macvlan-and-ipvlan/)

We can check by looking at the profile in LXD, from `lxc profile list` you should see a profile with a name similar to the UUID of the container then post the result of `lxc profile show <profile name>`

**Comment by tommyliverani** [comment]
<img width="864" alt="mac" src="https://user-images.githubusercontent.com/43218487/104707704-0b4a0300-571d-11eb-9b00-812ac81d7b75.PNG">

**Comment by gabrik** [comment]
Then it should be related to the MACVLAN issue, not strictly to fog05.

Because if it gets the IP address means that at least L2 is working.

From the container can you ping any machine in the network?
If not can you run `tracepath <IP address of a machine in the network>`, anyway with MACVLAN it is unlikely that you can reach the host machine and vice-versa.

**Comment by tommyliverani** [comment]
No I can't ping 
<img width="822" alt="trace" src="https://user-images.githubusercontent.com/43218487/104709273-00906d80-571f-11eb-8285-dd7ac5fb2cb2.PNG">

**Comment by gabrik** [comment]
Can you ping something on the Internet from the container? Like `ping -c 4 1.1.1.1`

**Comment by tommyliverani** [comment]
No
<img width="408" alt="ping" src="https://user-images.githubusercontent.com/43218487/104710591-8b259c80-5720-11eb-86a5-dcf8e1f28586.PNG">

**Comment by gabrik** [comment]
What does `ip r` in the container return?

**Comment by tommyliverani** [comment]
<img width="736" alt="ip" src="https://user-images.githubusercontent.com/43218487/104711130-42baae80-5721-11eb-9899-2be12cb52014.PNG">
