### ISSUE TITLE
[BUG]Could not compile zenoh-util module from Fog05 clone

### ISSUE THREAD

**Issue by heyong4725** [eclipse-fog05/fog05#214]
**Describe the bug**
With freshly cloned Fog05, I could not compile zenoh-util/src/backoff.rs.
However, I have no problem to compile zenoh repo itself, which contains zenoh-util module

**To Reproduce**
$ git clone https://github.com/eclipse-fog05/fog05.git
$ cd fog05
$ cargo build --release --all-targets

See error:

ubuntu@ecs-zenoh-yhe-01:~/fog05/fog05$ cargo build --release --all-targets
   Compiling zenoh-util v0.5.0-beta.5 (https://github.com/eclipse-zenoh/zenoh.git?branch=master#7e0f0bcc)
error[E0658]: use of unstable library feature 'renamed_spin_loop'
  --> /home/ubuntu/.cargo/git/checkouts/zenoh-cc237f2570fab813/7e0f0bc/zenoh-util/src/sync/backoff.rs:16:5
   |
16 | use std::hint::spin_loop;
   |     ^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #55002 <https://github.com/rust-lang/rust/issues/55002> for more information
   = help: add `#![feature(renamed_spin_loop)]` to the crate attributes to enable

**Expected behavior**
Expect no compilation error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux] Ubuntu
 - Version [e.g. 22] 18.04
 - Involved plugin (eg. KVM, LXD ...)

**Additional context**

**Comment by gabrik** [comment]
Hi @heyong4725,

I tested on a similar machine, but unfortunately, I was not able to reproduce your error.

Maybe it is a matter of rust version, I tested with the latest nightly `rustc 1.51.0-nightly (e708cbd91 2021-02-03)` .

Can you check your version (`rustc --version`) and if it is an old one please update it with `rustup update`.

**Comment by heyong4725** [comment]
Indeed, after I rustup upgrade (I was using rustc 1.48.0-nightly (fc2daaae6 2020-09-28)), the issue is gone.

What puzzled me was that I can compile zenho repo directly, but not fog05 repo.

**Comment by gabrik** [comment]
> What puzzled me was that I can compile zenho repo directly, but not fog05 repo.

Because in Zenoh repository there is a `rust-toolchain` that forces cargo/rustup to use the version of rust specified in that file.

While in fog05 we do not have that and we try to keep it working with the latest nightly. 

I hope this clarifies.

**Comment by heyong4725** [comment]
OK, I see the rust-toolchain here made a difference. 

Now I am trying to compile the fog05-networking-linux repo (following fog05.io installation), and encountered the following error:
buntu@ecs-zenoh-yhe-01:~/fog05/fog05-networking-linux$
ubuntu@ecs-zenoh-yhe-01:~/fog05/fog05-networking-linux$ cargo build --release --all-targets
   Compiling mnl-sys v0.2.0
   Compiling nftnl-sys v0.6.0
error: failed to run custom build command for `mnl-sys v0.2.0`

Caused by:
  process didn't exit successfully: `/home/ubuntu/fog05/fog05-networking-linux/target/release/build/mnl-sys-11425688c2dd4c48/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBMNL_LIB_DIR
  Minimum libmnl version: 1.0.3
  cargo:rerun-if-env-changed=LIBMNL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=LIBMNL_STATIC
  cargo:rerun-if-env-changed=LIBMNL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"libmnl\" \"libmnl >= 1.0.3\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package libmnl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libmnl.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'libmnl\' found\nPackage libmnl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libmnl.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'libmnl\' found\n" } }', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/mnl-sys-0.2.0/build.rs:30:14
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
ubuntu@ecs-zenoh-yhe-01:~/fog05/fog05-networking-linux$

Any suggestions?

**Comment by gabrik** [comment]
Hi @heyong4725,

You need some dependencies to be installed:

```
sudo apt install dnsmasq-base nftables libnftnl-dev libnfnetlink-dev libmnl-dev pkg-config libssl-dev
```


It seems that the step-by-step guide on the website was missing some steps about dependency installation, I have updated it, so now it should be fine.

**Comment by heyong4725** [comment]
Looks like those dependencies still are not enough:
ubuntu@ecs-zenoh-yhe-01:~/fog05/fog05-networking-linux$ cargo build --release --all-targets                Compiling nftnl-sys v0.6.0
   Compiling async-channel v1.5.1
error: failed to run custom build command for `nftnl-sys v0.6.0`

Caused by:
  process didn't exit successfully: `/home/ubuntu/fog05/fog05-networking-linux/target/release/build/nftnl-sys-3cbe512379d576a8/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBNFTNL_LIB_DIR
  Minimum libnftnl version: 1.0.6
  cargo:rerun-if-env-changed=LIBNFTNL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=LIBNFTNL_STATIC
  cargo:rerun-if-env-changed=LIBNFTNL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"libnftnl\" \"libnftnl >= 1.0.6\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Requested \'libnftnl >= 1.0.6\' but version of libnftnl is 1.0.5\nYou may find new versions of libnftnl at http://netfilter.org/projects/libnftnl/\n" } }', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/nftnl-sys-0.6.0/build.rs:44:14
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
ubuntu@ecs-zenoh-yhe-01:~/fog05/fog05-networking-linux$

**Comment by gabrik** [comment]
It seems that one of our dependecy does not support the version of libnftnl shipped with Ubuntu 18.04

```
thread 'main' panicked at 'called Result::unwrap() on an Err value: Failure { command: ""pkg-config" "--libs" "--cflags" "libnftnl" "libnftnl >= 1.0.6"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Requested 'libnftnl >= 1.0.6' but version of libnftnl is 1.0.5\nYou may find new versions of libnftnl at http://netfilter.org/projects/libnftnl/\n" } }',
```

It seems that the `nftnl/sys` support only for libnftnl 1.0.6 onwards, https://crates.io/crates/nftnl-sys

Therefore I guess that it will not compile on Ubuntu 18.04, do you have access to a more recent version of Ubuntu, like 20.04?

**Comment by heyong4725** [comment]
@gabrik I sure can create/find a Ubuntu 20.04 VM.

Now my question is: other than Ubuntu latest OS, can Fog05 run on any other platform/OS?

**Comment by gabrik** [comment]
We have succesfully tested on CentOS6 (even if it now dead), Debian 10, and Raspian.

Unforunately while the agent builds also on macOS the plugins will not, while on Windows we have a similar dependecy issue like the one you faced in Ubuntu18.04.


That said it should run on any Linux that does not poses issues w.r.t. depdendencies, as we depend on basic libraries and kernel capabilities that should be present in any Linux system. 
I have done a little reseach and seems that Ubuntu 18.04 ships a version on libnftnl that dates back to 2015.
