### ISSUE TITLE
[BUG] kvm migration fails

### ISSUE THREAD

**Issue by tommyliverani** [eclipse-fog05/fog05#215]
Migration command does not terminate and with systemctl status fos_kvm i I get this error:

feb 23 11:15:37 tommy-System-Product-Name fos_kvm[3164]: [2021-02-23 11:15:36,836] - [INFO] > < __fdu_observer() >  Error: 'dict' object has no attribute 'get_migration_properties'

I think it raises at line 602 of the plugin.

that's the fdu_descriptor:
{
    "id": "hello-world-docker",
    "name": "hello-world",
    "computation_requirements": {
        "cpu_arch": "x86_64",
        "cpu_min_freq": 0,
        "cpu_min_count": 1,
        "ram_size_mb": 2048.0,
        "storage_size_gb": 10
    },
    "image" : {
	"uri": "file:///var/lib/libvirt/images/ubuntu16.04-clone.qcow2",
	"checksum": "b500018f1cdd9eeaf6f5a787a6dfc1abc5409f851338484ba21e40956ac768a4",
	"format": "qcow2"
    },
    "storage": [],
    "hypervisor": "KVM",
    "migration_kind": "LIVE",
    "interfaces": [],
    "io_ports": [],
    "connection_points": [],
    "depends_on": []
}

I' m using:
fog05/now 0.2.1-1 amd64 [installed,local]
fog05-plugin-fdu-kvm/now 0.2.0-1 amd64 [installed,local]
fog05-plugin-fdu-lxd/now 0.2.0-1 amd64 [residual-config]
fog05-plugin-fdu-native/now 0.2.0-1 amd64 [installed,local]
fog05-plugin-net-linuxbridge/now 0.2.1-1 amd64 [installed,local]
fog05-plugin-os-linux/now 0.2.0-1 amd64 [installed,local]

on ubuntu 18.04

**Comment by gabrik** [comment]
This is related to the "old" OCaml version, it will not be fixed/investigated
