### ISSUE TITLE
Fog05 on microcontrollers

### ISSUE THREAD

**Issue by expploitt** [eclipse-fog05/fog05#216]
Hello,

I found fog05 as a good proposal in fog computing but I can't understand well the actual state of the project.

Is it available to use microcontrollers in a fog05 deployment? I understand, that microcontrollers uses as proxy a peer which has more resources, but..how does it work? Using  zenoh?

Thanks!

**Comment by gabrik** [comment]
Hi @expploitt,

We are currently investigating how to use fog05 in microcontrollers.
The design phase is almost done and as you pointed out the idea is to use a more capable node as a proxy and leverage on Zenoh between the two.

Anyway the current version does not yet implement the support for microcontrollers.

**Comment by expploitt** [comment]
Hello @gabrik, thanks for the information!
