### ISSUE TITLE
Failed deploy

### ISSUE THREAD

**Issue by expploitt** [eclipse-fog05/fog05#217]
Hello!

Today I try to deploy fog05 following the fog05.io documentation but when I try to start the services in the order indicated, it fails.

Does working properly the deploy since last commit yesterday?

Thanks

**Comment by gabrik** [comment]
Can you provide the output of the services that fails?

**Comment by expploitt** [comment]
The first service (zenoh):

```
● fos-zenoh.service
     Loaded: loaded (/lib/systemd/system/fos-zenoh.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-03-10 16:18:06 CET; 29min ago
    Process: 6025 ExecStartPre=/bin/bash -c /bin/systemctl set-environment ZIP=$( /var/fos/get-zip.sh ) (code=exited, status=0/SUCCESS)
    Process: 6033 ExecStartPre=/bin/bash -c /bin/systemctl set-environment NODEID=$( /usr/bin/fog05-agent --node-uuid) (code=exited, status=0/SUCCESS)
    Process: 6044 ExecStart=/usr/bin/zenohd --mem-storage /fos/global/** --mem-storage /fos/local/${NODEID}/** -l tcp/127.0.0.1:61189 -l unixsock-stream//tmp/fos-zenoh.sock -l tcp/${ZIP}:61189 --id ${NODEID} (code=exited, status=255/EXC>
   Main PID: 6044 (code=exited, status=255/EXCEPTION)

mar 10 16:18:06 moises-Aspire-A515-55 systemd[1]: fos-zenoh.service: Scheduled restart job, restart counter is at 5.
mar 10 16:18:06 moises-Aspire-A515-55 systemd[1]: Stopped fos-zenoh.service.
mar 10 16:18:06 moises-Aspire-A515-55 systemd[1]: fos-zenoh.service: Start request repeated too quickly.
mar 10 16:18:06 moises-Aspire-A515-55 systemd[1]: fos-zenoh.service: Failed with result 'exit-code'.
mar 10 16:18:06 moises-Aspire-A515-55 systemd[1]: Failed to start fos-zenoh.service.
```

**Comment by gabrik** [comment]
Can you share a more detailed log? You can get it with `journalctl -u fos-zenoh -n 25 --no-pager` 

The version of zenoh you are using is from master right?

**Comment by expploitt** [comment]
I use the version that is especified in the installation guide. 

´´´
$ wget https://download.eclipse.org/zenoh/zenoh/0.5.0-beta.5/zenohd_0.5.0~beta.5_amd64.deb
$ wget https://download.eclipse.org/zenoh/zenoh/0.5.0-beta.5/zenoh-storages_0.5.0~beta.5_amd64.deb
$ sudo apt install ./zenohd_0.5.0~beta.5_amd64.deb  ./zenoh-storages_0.5.0~beta.5_amd64.deb
´´´

I saw that the _cargo dev_ command generates a service file with the unit part as [unit] but should be instead [Unit].
Also, the fog-zenoh.service executed command in a terminal output:

´´´
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ZError { kind: InvalidLocator { descr: "Missing protocol: unixsock-stream//tmp/fos-zenoh.sock" }, file: "zenoh-protocol/src/link/locator.rs", line: 74, source: None }', /workdir/zenoh-router/src/runtime/orchestrator.rs:181:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
´´´

Thanks!

**Comment by gabrik** [comment]
> I use the version that is especified in the installation guide.
> 
> ```
> $ wget https://download.eclipse.org/zenoh/zenoh/0.5.0-beta.5/zenohd_0.5.0~beta.5_amd64.deb
> $ wget https://download.eclipse.org/zenoh/zenoh/0.5.0-beta.5/zenoh-storages_0.5.0~beta.5_amd64.deb
> $ sudo apt install ./zenohd_0.5.0~beta.5_amd64.deb  ./zenoh-storages_0.5.0~beta.5_amd64.deb
> ```

I should update the guide, fog05 tries always to follow the master of Zenoh.
I'll update that portion.

> I saw that the _cargo dev_ command generates a service file with the unit part as [unit] but should be instead [Unit].

Thanks, I'll fix that!

> Also, the fog-zenoh.service executed command in a terminal output:
>
> journalctl -u fos-zenoh -n 25 --no-pager
> 
> ```
> -- Logs begin at Fri 2021-01-22 08:07:21 CET, end at Thu 2021-03-11 10:00:28 CET. --
> mar 11 09:25:59 moipc fos-zenoh[548228]: [2021-03-11T08:25:59Z DEBUG zenoh_router::plugins] Plugins to load: []
> mar 11 09:25:59 moipc fos-zenoh[548228]: [2021-03-11T08:25:59Z DEBUG zenoh_util::lib_loader] Search for libraries libzplugin_*.so to load in ["/usr/local/lib", "/usr/lib", "/", "/usr/bin"]
> mar 11 09:25:59 moipc fos-zenoh[548228]: [2021-03-11T08:25:59Z DEBUG zenoh_router::plugins] Plugin storages loaded from /usr/lib/libzplugin_storages.so
> mar 11 09:25:59 moipc fos-zenoh[548228]: [2021-03-11T08:25:59Z DEBUG zenohd] Config: {"mode": "router", "listener": "tcp/127.0.0.1:61189,unixsock-stream//tmp/fos-zenoh.sock,tcp/172.16.5.92:61189", "peer": "", "add_timestamp": "true"}
> mar 11 09:25:59 moipc fos-zenoh[548228]: zenoh error: (Invalid id: 8710d370-59d7-446b-9b60-25ff96b90ca1 - Invalid character '-' at position 8) at zenoh-router/src/runtime/mod.rs:45.. Exiting...
> mar 11 09:25:59 moipc systemd[1]: fos-zenoh.service: Main process exited, code=exited, status=255/EXCEPTION
> mar 11 09:25:59 moipc systemd[1]: fos-zenoh.service: Failed with result 'exit-code'.
> mar 11 09:25:59 moipc systemd[1]: fos-zenoh.service: Scheduled restart job, restart counter is at 4.
> mar 11 09:25:59 moipc systemd[1]: Stopped Eclipse fog05 -- Eclipse Zenoh.
> mar 11 09:25:59 moipc systemd[1]: Starting Eclipse fog05 -- Eclipse Zenoh...
> mar 11 09:25:59 moipc systemd[1]: Started Eclipse fog05 -- Eclipse Zenoh.
> mar 11 09:25:59 moipc fos-zenoh[548274]: [2021-03-11T08:25:59Z DEBUG zenohd] zenohd v0.5.0-beta.5
> mar 11 09:25:59 moipc fos-zenoh[548274]: [2021-03-11T08:25:59Z DEBUG zenoh_util::lib_loader] Cannot search for libraries in /home/fos/.zenoh/lib: No such file or directory (os error 2)
> mar 11 09:25:59 moipc fos-zenoh[548274]: [2021-03-11T08:25:59Z DEBUG zenoh_router::plugins] Plugins to load: []
> mar 11 09:25:59 moipc fos-zenoh[548274]: [2021-03-11T08:25:59Z DEBUG zenoh_util::lib_loader] Search for libraries libzplugin_*.so to load in ["/usr/local/lib", "/usr/lib", "/", "/usr/bin"]
> mar 11 09:25:59 moipc fos-zenoh[548274]: [2021-03-11T08:25:59Z DEBUG zenoh_router::plugins] Plugin storages loaded from /usr/lib/libzplugin_storages.so
> mar 11 09:25:59 moipc fos-zenoh[548274]: [2021-03-11T08:25:59Z DEBUG zenohd] Config: {"peer": "", "add_timestamp": "true", "mode": "router", "listener": "tcp/127.0.0.1:61189,unixsock-stream//tmp/fos-zenoh.sock,tcp/172.16.5.92:61189"}
> mar 11 09:25:59 moipc fos-zenoh[548274]: zenoh error: (Invalid id: 8710d370-59d7-446b-9b60-25ff96b90ca1 - Invalid character '-' at position 8) at zenoh-router/src/runtime/mod.rs:45.. Exiting...
> mar 11 09:25:59 moipc systemd[1]: fos-zenoh.service: Main process exited, code=exited, status=255/EXCEPTION
> mar 11 09:25:59 moipc systemd[1]: fos-zenoh.service: Failed with result 'exit-code'.
> mar 11 09:26:00 moipc systemd[1]: fos-zenoh.service: Scheduled restart job, restart counter is at 5.
> mar 11 09:26:00 moipc systemd[1]: Stopped Eclipse fog05 -- Eclipse Zenoh.
> mar 11 09:26:00 moipc systemd[1]: fos-zenoh.service: Start request repeated too quickly.
> mar 11 09:26:00 moipc systemd[1]: fos-zenoh.service: Failed with result 'exit-code'.
> mar 11 09:26:00 moipc systemd[1]: Failed to start Eclipse fog05 -- Eclipse Zenoh.
> ```

I guess the problem is because that version was not supporting the way we pass the ID to the Zenoh router, using Zenoh from master should solve this.

**Comment by expploitt** [comment]
Okey, I will try with tzenoh master.

Thanks

**Comment by gabrik** [comment]
Please wait until https://github.com/eclipse-zenoh/zenoh/pull/72 is merged, so you can generate the Debian packages for Zenoh.

**Comment by expploitt** [comment]
Okey, I was compiling Zenoh master and I was wondering how to generate de debian package. Thanks!

**Comment by gabrik** [comment]
Now that it is merged you can `git pull` and then generate the Debian packages:

```
$ cargo deb -p zenoh
....
    Finished release [optimized] target(s) in 2m 52s
/home/ato/Workspace/zenoh/target/debian/zenohd_0.5.0~beta.8_amd64.deb
$ cargo deb -p zenoh-storages
...
    Finished release [optimized] target(s) in 2m 04s
/home/ato/Workspace/zenoh/target/debian/zenoh-storages_0.5.0~beta.8_amd64.deb
```
You fill have both debian files under `./target/debian` you can install them with apt `sudo apt install ./target/debian/* -y`

**Comment by expploitt** [comment]
Thanks @gabrik ! I remember you that the cargo deb generate the [unit] incorrectly.

I close the issue :)

**Comment by gabrik** [comment]
I fixed that for the Agent and Zenoh.

I'm going to fix it also for the plugins!

**Comment by expploitt** [comment]
Hello @gabrik, now I'm trying to deploy force as in the tutorial, but when I compile with make the go code...

```
go build -o force src/app.go src/force.go src/main.go
# github.com/atolab/zenoh-go
../../../../go/pkg/mod/github.com/atolab/zenoh-go@v0.3.1/c_callbacks.go:6:10: fatal error: zenoh/codec.h: No such file or directory
    6 | #include <zenoh/codec.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:9: all] Error 2
```

Thanks!

**Comment by gabrik** [comment]
Using the latest version you do not need to build or use it.

You can just use the CLI tool `fosctl`.

Then you can instantiate one of the examples in https://github.com/eclipse-fog05/fog05/tree/master/fog05-fosctl/examples like fdu-native.yaml.

The instantiation goes like this:

```
$ fosctl fim add fdu fdu-native.yaml
d316b680-206d-4f2b-9794-0df6cb66caec # this is returned by fog05
$ fosctl fim add instance d316b680-206d-4f2b-9794-0df6cb66caec
ec9b4742-b2c3-475b-a880-532e5514116b # also returned by fog05
```

Then if you want you can see the output with `tail -f /var/fos/native-hypervisor/ec9b4742-b2c3-475b-a880-532e5514116b/ec9b4742-b2c3-475b-a880-532e5514116b.out`
