### ISSUE TITLE
fog05 Networking cross-compilation failed

### ISSUE THREAD

**Issue by expploitt** [eclipse-fog05/fog05#221]
Hello

I'm building and generating .deb packages  of fog05 for RPI 4 and when I compile the networking plugin I get the following error:

```
error: failed to run custom build command for `mnl-sys v0.2.0`

Caused by:
  process didn't exit successfully: `/home/ubuntu/nextperception/fog05deploy/fog05-networking-linux/target/release/build/mnl-sys-f347f211a0440989/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBMNL_LIB_DIR
  Minimum libmnl version: 1.0.3
  cargo:rerun-if-env-changed=LIBMNL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_armv7-unknown-linux-gnueabihf
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_armv7_unknown_linux_gnueabihf
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_armv7-unknown-linux-gnueabihf
  cargo:rerun-if-env-changed=PKG_CONFIG_armv7_unknown_linux_gnueabihf
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_armv7-unknown-linux-gnueabihf
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_armv7_unknown_linux_gnueabihf
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CrossCompilation', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/mnl-sys-0.2.0/build.rs:30:14
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
   Compiling http-body v0.4.0
   Compiling unicode-normalization v0.1.17
   Compiling nftnl-sys v0.6.0
   Compiling mnl-sys v0.2.0
   Compiling httparse v1.3.5
   Compiling rustversion v1.0.4
   Compiling unic-ucd-segment v0.9.0
error: failed to run custom build command for `mnl-sys v0.2.0`
```

I building the code in a cross-compilation environment, as the RPI spends a lot of time. I used:
```
  targetflag=armv7-unknown-linux-gnueabihf

  cargo build --release --target=$targetflag --all-targets
  cargo deb --target=$targetflag
```

**Comment by gabrik** [comment]
Hi, @expploitt I guess it is because it is not able to find the dependencies.
As you can see it is failing in building the `mnl-sys` crate which depends on `libnftnl-dev`, `libnfnetlink-dev` and `libmnl-dev`.

I think that in order to cross-compile you need them installed for the architecture you are compiling.
We are currently investigating the cross-compile on the Eclipse CI infrastructure in order to provide nightly builds for different architectures.

**Comment by gabrik** [comment]
Hi @expploitt,

This depends on this issue: https://github.com/mullvad/nftnl-rs/issues/41

**Comment by gabrik** [comment]
If you set the correct environment variables it should build without any issue:

Solved by setting the correct environment variables: `PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig` and `PKG_CONFIG_ALLOW_CROSS=1`

**Comment by expploitt** [comment]
Should be /aarch64-linux-gnu/ or/ armv7-unknown-linux-gnueabihf/ ? I'm trying to compile for a RPi

**Comment by gabrik** [comment]
Depends on the OS you have on the RPi.

I usually use Ubuntu 20.04 for arm64 so aarch64.
You can check with `uname -m`

In any case, make sure you have the library installed, the proper pkg-config for the architecture and, the architecture configured in dpkg.



For aarch64:
```
$ dpkg --add-architecture arm64
$ sudo apt install crossbuild-essential-arm64 pkg-config-aarch64-linux-gnu libnftnl-dev:arm64 libnfnetlink-dev:arm64 libmnl-dev:arm64
```

For armhf (armv7l reported by `uname -m`):
```
$ dpkg --add-architecture armhf
$ sudo apt install crossbuild-essential-armhf pkg-config-arm-linux-gnueabihf libnftnl-dev:armhf libnfnetlink-dev:armhf libmnl-dev:armhf
```

You may also need a proper cargo configuration, you can find examples for that in our [Jenkins file](https://github.com/eclipse-fog05/fog05/blob/master/Jenkinsfile#L65)


Please be aware that the `-dev` libraries will rewrite the one you have for your current system.
So if you need to build for `x86_64` you need to reinstall them.

**Comment by gabrik** [comment]
@expploitt we now provide a script to facilitate the cross-build: https://github.com/eclipse-fog05/fog05/blob/master/build-cross.sh 

I'm going to close this issue as that script provides automatic cross-build.

**Comment by expploitt** [comment]
Thanks!!
