### ISSUE TITLE
[BUG] Build-cross.sh error

### ISSUE THREAD

**Issue by expploitt** [eclipse-fog05/fog05#227]
Hello!

I was testing the new funcionality implemented last week for easily cross-compilation and I found the following error when execution for `$ARCH=arm64`

```
mv: cannot stat '/tmp/debian/*.deb': No such file or directory
```

Thanks!

**Comment by gabrik** [comment]
Hi, can you provide the last 10 lines of the output?
That folder should be created when copying the generated Debian files from the container, maybe it was not able to copy them from the container.
