### ISSUE TITLE
[BUG] Compile error with Rust 1.55.0 (stable)

### ISSUE THREAD

**Issue by sjames** [eclipse-fog05/fog05#231]
**Describe the bug**
I checked out the fog05 repository and tried to build it on Ubuntu 20.04.  shared_memory v 0.11.4 fails to compile. This package is a dependency of zenoh.

`
   Compiling shared_memory v0.11.4
error[E0164]: expected tuple struct or tuple variant, found associated function `nix::Error::Sys`
  --> /home/sjames/.cargo/registry/src/github.com-1ecc6299db9ec823/shared_memory-0.11.4/src/unix.rs:87:13
   |
87 |         Err(nix::Error::Sys(Errno::EEXIST)) => return Err(ShmemError::MappingIdExists),
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `fn` calls are not allowed in patterns
   |
   = help: for more information, visit https://doc.rust-lang.org/book/ch18-00-patterns.html

`
**To Reproduce**
1. Check out fog05 github repo
2. cargo build

**Expected behavior**
Build must succeed

**Desktop (please complete the following information):**
 - OS: Linux
 - Version Ubuntu 20.04

**Comment by gabrik** [comment]
Hi @sjames,

Eclipse fog05 does not build with rust stable it requires nightly 

```bash
rustup default nightly
cargo update
cargo build --all-targets
```

This was tested on an Ubuntu 20.04 and was working

**Comment by sjames** [comment]
@gabrik . I tried this just now , but had the same error.  I also realized that I have Ubuntu 18.04 on this computer, sorry about saying I was using 20.04.

Which version of nightly are you using?

![image](https://user-images.githubusercontent.com/405933/135057552-b69dd2b5-7972-45c6-885e-301d3bad8fa2.png)

**Comment by gabrik** [comment]
It seems it is getting the wrong version of the `shared_memory` crate, in some Linux installations.

I'll give a deeper look and come back with a solution/PR.

**Comment by gabrik** [comment]
It should be solved now, please let me know and reopen this issue if necessary

**Comment by sjames** [comment]
Thank you. It builds now.
