### ISSUE TITLE
[BUG] Hello world example is not working

### ISSUE THREAD

**Issue by BDUG** [eclipse-fog05/fog05#233]
**Describe the bug**
After successful installation of the latest fog05 incl. zenoh (et al) I am not able to get the "Hello world" example "fos_deploy.py" running. I receive the failure message "Exception: Unable to open zenoh session (error code: 13)."

The error appears here:
  File "fos_deploy.py", line 11, in <module>
    api = FIMAPI()

I also verified my zenoh installation by just publishing values via the command "z_pub". This worked perfect. 

**To Reproduce**
Steps to reproduce the behavior: Just follow your howto 

**Expected behavior**
Get the "hello world" deployment running. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 20.x LTS
 - Involved plugin (eg. KVM, LXD ...)

**Comment by gabrik** [comment]
Hi @BDUG,

this project is in maintenance, therefore it will not receive any update or bug fix for the time being.

That said, where did you find the `fos_deploy.py` script? 
The master version of fog05 does not provide any working Python API and all interaction is done via the CLI tool `fosctl`.
And all the deployment is managed via `yaml` files, as in the example repository: https://github.com/eclipse-fog05/examples

**Comment by BDUG** [comment]
THX
